# Generated by Django 5.2 on 2025-04-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
