# Generated by Django 5.2 on 2025-04-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_stadiumbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
