# Generated by Django 5.2 on 2025-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0004_stadium_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
