# Generated by Django 5.2 on 2025-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0005_stadium_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiumbooking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stadiumbooking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='stadiumbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stadiumbooking',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
